language: c
script: make
script:
    - make -C test all
    - ./test/saxml ./vectors/test1.xml > out1.txt
    - diff out1.txt ./vectors/result1.txt 
    - ./test/saxml ./vectors/test2.xml > out2.txt
    - diff out2.txt ./vectors/result2.txt 
    - ./test/saxml ./vectors/test3.xml > out3.txt
    - diff out3.txt ./vectors/result3.txt 
